{"name": "test_mul[mul_failed]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 2", "trace": "self = <pytest_9916.test_calc_new.TestCalc object at 0x00000000036A8490>, start_end = None, a = 2, b = 0, expect = 2\n\n    @pytest.mark.run(order=3)\n    @pytest.mark.parametrize(\n        'a, b, expect',\n        datas['mul']['datas'],\n        ids=datas['mul']['myid']\n    )\n    def test_mul(self, start_end, a, b, expect):\n        result = self.mul(a, b)\n        if isinstance(result, float):\n            result = round(result, 2)\n>       assert result == expect\nE       assert 0 == 2\n\ntest_calc_new.py:92: AssertionError"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "0"}, {"name": "expect", "value": "2"}], "start": 1613559264254, "stop": 1613559264255, "uuid": "113fef1a-b6e2-4386-91fd-8a20049b66d7", "historyId": "866cc48a78570b693af6ee0313d94208", "testCaseId": "fe6bda14bd0e8d9a8af1eb7bd6c20851", "fullName": "test_calc_new.TestCalc#test_mul", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "SKY-20190112HVA"}, {"name": "thread", "value": "7816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}