{"name": "test_sub[sub_failed]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 0", "trace": "self = <pytest_9916.test_calc_new.TestCalc object at 0x00000000036AD190>, start_end = None, a = 2, b = 0, expect = 0\n\n    @pytest.mark.run(order=2)\n    @pytest.mark.parametrize(\n        'a, b, expect',\n        datas['sub']['datas'],\n        ids=datas['sub']['myid']\n    )\n    def test_sub(self, start_end, a, b, expect):\n        result = self.sub(a, b)\n        if isinstance(result, float):\n            result = round(result, 2)\n>       assert result == expect\nE       assert 2 == 0\n\ntest_calc_new.py:79: AssertionError"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "0"}, {"name": "expect", "value": "0"}], "start": 1613559264197, "stop": 1613559264198, "uuid": "07e002de-b732-4270-a944-061e2fca8ca3", "historyId": "e8054ee46b0088e8aaddea35a3e702c3", "testCaseId": "a1506a2b3b61cae69056fcb454df3b1b", "fullName": "test_calc_new.TestCalc#test_sub", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "SKY-20190112HVA"}, {"name": "thread", "value": "7816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}